.TH daemonizer 1 "2008-07-16"

.SH NAME
daemonizer \- Program management utility

.SH SYNOPSIS
.B daemonizer [ -R root ]

.SH DESCRIPTION
A tool to execute other programs, possibly taking daemon-like steps, possibly
repeatedly according to various parameters, possibly with various supporting
structure such as pidlocks.

.SH OPTIONS

.SH NOTES

.SH SEE ALSO
dank(3dank), daemon(1)
